language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"


before_script:
  - sudo apt-get update -qq
  - pip install --upgrade pip
  - pip install coverage
  - pip install pep8
  - pip install pylint
  - pip install -e .

install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover -s test
  - coverage report -m
