# -*- coding: utf-8 -*-
# Copyright (c) 2017, AL.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for pytrr.

This file is generated by the script ``setup_version.py``.
"""
SHORT_VERSION = '0.3.0'
VERSION = '0.3.0'
FULL_VERSION = '0.3.0'
GIT_REVISION = 'e996c5d63d23de675b062fa381fabbfc1fb99367'
GIT_VERSION = '0.3.0'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
