# -*- coding: utf-8 -*-
# Copyright (c) 2017, Anders Lervik.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for pytrr.

This file is generated by the script ``setup_version.py``.
"""
SHORT_VERSION = '0.4.0'
VERSION = '0.4.0'
FULL_VERSION = '0.4.0'
GIT_REVISION = '96ce0810f26cb9198f3d10fb3c1e76514ed27668'
GIT_VERSION = '0.4.0'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
