# -*- coding: utf-8 -*-
# Copyright (c) 2017, AL.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for pytrr.

This file is generated by the script ``setup_version.py``.
"""
SHORT_VERSION = '0.1.0.dev0'
VERSION = '0.1.0.dev0'
FULL_VERSION = '0.1.0.dev0'
GIT_REVISION = '5aa5508feacbc5c51cf2f3a85357d37676edce22'
GIT_VERSION = '0.1.0.dev0+5aa5508'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
